sudo: required
services:
  - docker

before_install:
  - docker build -t deadpoet/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deadpoet/docker-react npm run test -- --coverage

deploy:
  #refer section 103
  provider: elasticbeanstalk 
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-811237443234"
  #app name acts as the bucket-path
  bucker_path: "docker-react"
  on:
    branch: master
  #Need API keys to provide access to travis to use AWS EBS
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"